version: '2'
services:
  springbootrestdistsystem101-app:
    image: springbootrestdistsystem101
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://springbootrestdistsystem101-postgresql:5432/SpringBootRestDistSystem101
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  springbootrestdistsystem101-postgresql:
    extends:
      file: postgresql.yml
      service: springbootrestdistsystem101-postgresql
